// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: user/user_std_service.proto

package protoc_gen_go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserStdService_UpdateUser_FullMethodName = "/userstdservice.UserStdService/UpdateUser"
	UserStdService_GetUser_FullMethodName    = "/userstdservice.UserStdService/GetUser"
)

// UserStdServiceClient is the client API for UserStdService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserStdServiceClient interface {
	UpdateUser(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Empty, error)
	GetUser(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type userStdServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserStdServiceClient(cc grpc.ClientConnInterface) UserStdServiceClient {
	return &userStdServiceClient{cc}
}

func (c *userStdServiceClient) UpdateUser(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, UserStdService_UpdateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userStdServiceClient) GetUser(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, UserStdService_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserStdServiceServer is the server API for UserStdService service.
// All implementations must embed UnimplementedUserStdServiceServer
// for forward compatibility.
type UserStdServiceServer interface {
	UpdateUser(context.Context, *Request) (*Empty, error)
	GetUser(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedUserStdServiceServer()
}

// UnimplementedUserStdServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserStdServiceServer struct{}

func (UnimplementedUserStdServiceServer) UpdateUser(context.Context, *Request) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedUserStdServiceServer) GetUser(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedUserStdServiceServer) mustEmbedUnimplementedUserStdServiceServer() {}
func (UnimplementedUserStdServiceServer) testEmbeddedByValue()                        {}

// UnsafeUserStdServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserStdServiceServer will
// result in compilation errors.
type UnsafeUserStdServiceServer interface {
	mustEmbedUnimplementedUserStdServiceServer()
}

func RegisterUserStdServiceServer(s grpc.ServiceRegistrar, srv UserStdServiceServer) {
	// If the following call pancis, it indicates UnimplementedUserStdServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserStdService_ServiceDesc, srv)
}

func _UserStdService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserStdServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserStdService_UpdateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserStdServiceServer).UpdateUser(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserStdService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserStdServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserStdService_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserStdServiceServer).GetUser(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// UserStdService_ServiceDesc is the grpc.ServiceDesc for UserStdService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserStdService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "userstdservice.UserStdService",
	HandlerType: (*UserStdServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateUser",
			Handler:    _UserStdService_UpdateUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserStdService_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/user_std_service.proto",
}
